////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated. 
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace Dent_Oil_Canning2
//{


//    public partial class OilCanningBulkInput
//    {

//        /// <summary>
//        /// lblErrorMSG control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Label lblErrorMSG;

//        /// <summary>
//        /// FileUpload1 control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;

//        /// <summary>
//        /// btnLoadExcel control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button btnLoadExcel;

//        /// <summary>
//        /// btnExport control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button btnExport;

//        /// <summary>
//        /// gvOilCanningData control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.GridView gvOilCanningData;
//    }
//}
